import streamlit as st
from PIL import Image
import datetime
import uuid
from gradcam_engine import analyze_image
from explainer import generate_forensic_explanation

st.set_page_config(page_title="ForensIQ — Deepfake Forensic Report", layout="wide", page_icon="🔍")

st.markdown("""
<style>
.report-header {
    border-bottom: 3px solid #1a1a2e;
    padding-bottom: 16px;
    margin-bottom: 24px;
}
.case-id {
    font-family: monospace;
    color: #888;
    font-size: 13px;
}
.verdict-box {
    padding: 20px 24px;
    border-radius: 8px;
    margin: 16px 0;
}
.verdict-fake {
    background: rgba(239, 68, 68, 0.1);
    border-left: 4px solid #ef4444;
}
.verdict-real {
    background: rgba(34, 197, 94, 0.1);
    border-left: 4px solid #22c55e;
}
.section-label {
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: #888;
    font-weight: 600;
    margin-bottom: 8px;
}
.region-row {
    display: flex;
    justify-content: space-between;
    padding: 6px 0;
    border-bottom: 1px solid #eee;
    font-size: 14px;
}
</style>
""", unsafe_allow_html=True)

st.markdown('<div class="report-header">', unsafe_allow_html=True)
st.title("🔍 ForensIQ")
st.caption("Deepfake Forensic Analysis — Explainable AI for Investigators")
st.markdown('</div>', unsafe_allow_html=True)

uploaded_file = st.file_uploader("Upload an image for forensic analysis", type=["jpg", "jpeg", "png"])

if uploaded_file:
    case_id = str(uuid.uuid4())[:8].upper()
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

    image = Image.open(uploaded_file)

    with st.spinner("Running forensic analysis..."):
        result = analyze_image(image)
        explanation = generate_forensic_explanation(
            result["verdict"], result["confidence"], result["region_activations"]
        )

    # Report header block
    col1, col2 = st.columns([3, 1])
    with col1:
        st.markdown(f"**Case ID:** `{case_id}`  |  **Analyzed:** {timestamp}  |  **File:** {uploaded_file.name}")
    with col2:
        st.markdown(f"<div class='case-id'>FORENSIQ-{case_id}</div>", unsafe_allow_html=True)

    st.divider()

    # Verdict box
    verdict_class = "verdict-fake" if result["verdict"] == "FAKE" else "verdict-real"
    verdict_color = "#ef4444" if result["verdict"] == "FAKE" else "#22c55e"
    st.markdown(f"""
    <div class="verdict-box {verdict_class}">
        <div style="font-size: 13px; color: #888; margin-bottom: 4px;">DETECTION RESULT</div>
        <div style="font-size: 32px; font-weight: 700; color: {verdict_color};">
            {result['verdict']} — {result['confidence']}% confidence
        </div>
    </div>
    """, unsafe_allow_html=True)

    # Images side by side
    img_col1, img_col2 = st.columns(2)
    with img_col1:
        st.markdown('<div class="section-label">ORIGINAL IMAGE</div>', unsafe_allow_html=True)
        st.image(result["original_resized"], use_container_width=True)
    with img_col2:
        st.markdown('<div class="section-label">MODEL ATTENTION MAP</div>', unsafe_allow_html=True)
        st.image(result["overlay_image"], use_container_width=True)
        st.caption("Highlighted regions show where the model focused when making its determination")

    st.divider()

    # Explanation
    st.markdown('<div class="section-label">FORENSIC SUMMARY</div>', unsafe_allow_html=True)
    st.markdown(f"<div style='font-size: 15px; line-height: 1.7; padding: 4px 0;'>{explanation}</div>", unsafe_allow_html=True)

    st.divider()

    # Region breakdown
    st.markdown('<div class="section-label">ATTENTION REGION BREAKDOWN</div>', unsafe_allow_html=True)
    for r in result["region_activations"][:5]:
        pct = min(r["activation"] * 100, 100)
        st.markdown(f"""
        <div class="region-row">
            <span>{r['region'].title()}</span>
            <span style="font-family: monospace; color: {'#ef4444' if pct > 60 else '#888'}">{pct:.0f}%</span>
        </div>
        """, unsafe_allow_html=True)

    st.divider()
    st.caption("This report is generated by an automated AI system for investigative support and should be reviewed by a qualified analyst. Model: EfficientNet-B0, 95% validation accuracy.")

else:
    st.markdown("""
    ### How ForensIQ Works
    1. Upload an image suspected of being AI-generated or manipulated
    2. The model runs binary classification (real vs. fake) with confidence scoring
    3. Grad-CAM generates an attention map showing which facial regions drove the decision
    4. Claude reads the saliency pattern and writes a plain-English forensic summary
    5. Output is a structured report an investigator can act on — not a raw model score

    **Model:** EfficientNet-B0 fine-tuned for deepfake detection, 95% validation accuracy
    """)